NatronGitHub/Natron

README.md

This is just some general cleanup to the README.
- Clean up the parentheses on the Help Wanted Qt line
- Change "32 bits floating point" to "32-bit floating point"; I'm sorry if "32 bits" was intentional, I didn't mean to cause any offense
- Fix "easily editable by human"
- Change the line wrap and remove double space on "Smooth & accurate zooming/panning"
- Change the line wrap on "Multi-plane"

Minor formatting fixes in README.md

---

CHANGELOG.md
Gui/Edge.cpp
INSTALL_LINUX.md

add compilation instruction for mint distribution
add qmake issue fix
make hidden inputs visible when a node is selected (even if "hide inputs" is checked in properties panel as nuke does)
this is my first PR on github so tell me if i did anything wrong

compilation instruction for linux mint and better hidden input behaviour

---

tools/jenkins/include/scripts/build-Linux-sdk.sh

Please read the [contribution guidelines](https://github.com/MrKepzie/Natron/blob/master/CONTRIBUTING.md), and be sure we have a [Contributor License Agreement](http://natron.fr/cla) on record with the project.
LinuxSDKBuildScriptFix-335
Since GCC 8.2.0 will not build with ISL 0.20, this fix sets the ISL version to 0.19 instead when GCC is version 8.2.0.

LinuxSDKBuildScriptFix-335

---

tools/jenkins/include/patches/bison/0001-fflush-adjust-to-glibc-2.28-libio.h-removal.patch
tools/jenkins/include/patches/bison/0002-fflush-be-more-paranoid-about-libio.h-change.patch
tools/jenkins/include/patches/breakpad/0002-Replace-remaining-references-to-struct-ucontext-with.patch
tools/jenkins/include/patches/gdb/gdb-Fix-ia64-defining-TRAP_HWBKPT-before-including-g.patch
tools/jenkins/include/patches/m4/m4-1.4.18-glibc-change-work-around.patch
tools/jenkins/include/patches/nasm/0001-Remove-invalid-pure_func-qualifiers.patch
tools/jenkins/include/scripts/build-Linux-sdk.sh

4 Fixes for the NatronSDK Linux build script:
m4: The gnulib bundled with m4 does not detect glibc version 2.28 and up properly.
Patch added to fix m4 build.
Bison: does not detect glibc version 2.28 and up properly.
2 patches added to fix bison build.
nasm: patch to fix building nasm with GCC 8.x.x.
Patch found here: https://github.com/spack/spack/pull/8307
fontconfig: fontconfig did not build due to a missing uuid, which is part of util-linux, which is only built AFTER fontconfig. Switching the build order of fontconfig and util-linux in the script fixes this issue.

Natron sdk linux fixes

---

tools/jenkins/common.sh
tools/jenkins/include/scripts/build-Linux-sdk.sh

NatronSDK/Linux/fixes
Additional fixes to the Natron SDK Linux build script
* Updated source URLs: qtwebkit, bzip2, mariadb, mesa, ImageMagick6, ImageMagick7, Qt 4.
* Modified THIRD_PARTY_SRC_URL to point to source packages on SourceForge.
* Temporarily disabled Qt 5.6 and pyside 2.

Natron sdk/linux/fixes

---

tools/jenkins/include/scripts/build-Linux-sdk.sh

Build of _libraw_ is missing from tools/jenkins/include/scripts/build-Linux-sdk.sh, causing the build of Natron to fail.
Added 'build libraw' to the script.

Fix missing libraw

---

tools/jenkins/include/scripts/pkg/poppler-glib.sh

ReadPDF requires UNSTABLE_API_ABI_HEADERS enabled in poppler-glib.

tools: fix poppler-glib on Linux

---

Engine/GenericSchedulerThread.cpp
Engine/NodeMain.cpp
Engine/OutputSchedulerThread.cpp

I noticed failing connects while running Natron, switched WatcherCallerArgsPtr to GenericWatcherCallerArgsPtr.

Engine: fix taskFinished connects that uses WatcherCallerArgsPtr

---

tools/jenkins/build-natron.sh

PySide and Shiboken are located in SDK/qt4 and are not included when running Tests on CentOS, and the tests will not run. Adding PYTHONPATH will include the modules and the tests will run.

tools: added PYTHONPATH on Linux when running Tests in build-natron.sh

---

Gui/Gui.cpp

Stop the viewers when abortProject is triggered. This will avoid thread hangs (or crashes) if you quit Natron (or close the project) while playback is running.
Issue #181

Gui: stop viewers when we abortProject

---

Engine/RotoContext.cpp
Engine/RotoContext.h
Engine/RotoDrawableItem.cpp
Gui/RotoPanel.cpp

(issues #420 and #205) :
* Prevent slaving knobs when the selection is a layer
* commented out (and add this explanation) an assert that
popup in debug when creating 2 layers in a row
I made a docker release with this fix. That folder contain 2 natron file that now work correctly when clicking on layer
https://github.com/Ivanohe73/Natron/releases/tag/v2.3.15-rc7-roto

Rotopaint error when working with multiple layers

---

Engine/AppManager.cpp
Engine/NodeDocumentation.cpp

Fixes the following errors
- undefined reference to Natron::AppManager::loadProjectFromFileFunction() in AppManager.cpp
- no member named 'isEmpty' in NodeDocumentation.cpp
- no viable conversion to 'QString' in NodeDocumentation.cpp

Fix some build errors

---

Gui/SplashScreen.cpp

Removed ``Qt::ToolTip`` and ``Qt::X11BypassWindowManagerHint`` from window flags on the SplashScreen since they force always on top.
This is related to issue #303 and has been tested on Linux and Windows.
*Totaly forgot about this commit, sorry :)*

SplashScreen: remove window flags

---

Documentation/source/guide/tutorials-imagesequence.rst

After going through some documentation ffmpeg now can use "-sws_flags" which can embed YUV chroma into RGB colorspace in full.

YUV force coversion method updated

---

App/App.pro
App/NatronApp_main.cpp
Engine/Settings.cpp
Engine/Settings.h

Console output on Windows now behaves as on Linux/macOS (output to parent as default). A separate console window can be enabled in "Preferences"=>"User Interface"=>"Enable console window", this enables the old Windows console behavior present in 2.3.15 and older.
Test build: https://github.com/rodlie/Natron/releases/download/console1/Natron-console-202007181854-6593003-Windows-64-no-installer.zip

App: handle console output on Windows

---

global.pri

Windows 10 introduced user fonts, and is the preferred (and default) place to install fonts.

fontconfig: detect user installed fonts on Windows 10

---

tools/jenkins/common.sh

While trying to build Natron, I noticed it deleted every single file in /tmp that wasn't system protected. 
This is caused by the "rm -rf" line in build-Linux-sdk.sh, where TMP_PATH is set to /tmp. I tracked this down to common.sh assuming WORKSPACE is defined. When it isn't, TMP_PATH resolves to /tmp. To resolve this I provided a default workspace. 
Where "rm -rf" is called: 
https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/include/scripts/build-Linux-sdk.sh#L432

Provide WORKSPACE variable if it doesn't exist

---

Gui/SequenceFileDialog.cpp
Gui/SequenceFileDialog.h

Some minor UX changes to SequenceFileDialog.
I moved the file type combo box beside the filename and the open/save button beside the cancel button, as this makes more sense IMHO. I also added the extensions to the filter, and set the default filter on init (if you for example open/save a project file your filter is set to *.ntp as default).

SequenceFileDialog (UX) changes

---

Documentation/source/guide/getstarted-troubleshooting.rst

Added in `getstarted-troubleshooting.rst` that user shall set  No. of OpenGL Context to 5 if 
`Shadertoy3: Can not render: glGetString(GL_VERSION) failed error` appears.

Documentation => added shadertoy troubleshoot

---

Gui/TimeLineGui.cpp

Fix for issue #567. The alpha cursor will now snap to nearest frame.
*I forgot to submit this one last week, better late than never :)*

Gui/TimeLineGui: snap alpha cursor to nearest frame

---

Gui/GuiResources.qrc
Gui/Resources/Stylesheets/mainstyle.qss

No longer uses SVG because it turns out it doesn't work properly in macOS when compiled.  Doesn't remove source SVG files from the folder.
Hopefully fixes #590.

Restores tab close PNG files

---

Engine/Project.cpp

Thanks for changing to "Project Format" for consistency!  I've made a few other minor improvements to grammar, consistency of node names, and descriptions of features.  This just touches tooltips, nothing else.
Most controversial change here is probably "In most cases this should match your plate resolution".  I think it's helpful but up for discussion.

Project settings tooltip text update

---

Gui/DockablePanel.cpp

QLineEdit triggers editingFinished when focus changes, this creates issues when we open a dialog based on this signal and return focus to the widget when done.
https://bugreports.qt.io/browse/QTBUG-40
Example: The node rename error dialog is triggered twice and after that focus is returned to the QLineEdit, on Windows this will trigger editingFinished again, resulting in an (almost) endless loop.
https://user-images.githubusercontent.com/34516798/112739504-1c14c180-8f75-11eb-90b9-b49d5120ea01.mp4

Gui/DockablePanel: connect to returnPressed instead of editingFinished for _nameLineEdit

---

Engine/EffectInstance.cpp
Engine/EffectInstance.h
Engine/Knob.cpp
Engine/Knob.h
Engine/KnobSerialization.cpp
Engine/KnobSerialization.h
Engine/Node.h
Engine/NodeGroupSerialization.cpp
Engine/NodeMain.cpp
Engine/NodePrivate.h
Engine/Project.cpp
Engine/ProjectPrivate.cpp
Engine/TrackMarker.cpp
Engine/TrackMarker.h
Gui/MultiInstancePanel.cpp
Gui/MultiInstancePanel.h
Gui/NodeGraph40.cpp
Gui/NodeGraph45.cpp
Gui/NodeGraphPrivate10.cpp
Gui/NodeGraphUndoRedo.cpp
Gui/PythonPanels.cpp
Gui/PythonPanels.h

Restoring links is now done in two passes:
1. Save the links during deserialization in the KnobI
2. Restore the links once all nodes were created

fix issue #568

---

Engine/RotoContext.cpp
Engine/RotoContext.h
Engine/RotoItem.cpp
Gui/RotoPanel.cpp
Gui/RotoPanel.h

#404 Added signal itemGloballyActivatedChanged on RotoContext, triggered when RotoItem has globallyActivated changed, so UI can update when changed via Python

#404 Added signal itemGloballyActivatedChanged on RotoContext
